### ISSUE TITLE
Change the title of the application!

### ISSUE THREAD

**Issue by Tuhin-thinks** [Tuhin-thinks/React-DirBrowser#9]
I am pretty late at doing this! But, lets change the title of the application!

**Comment by vikramnagwal** [comment]
change title to what??

**Comment by Tuhin-thinks** [comment]
> change title to what??

If you launch the application, it still shows "React App" the default one!

**Comment by vikramnagwal** [comment]
Please confirm the title you want to replace with the React app. Let me know the exact title you would like to substitute.

**Comment by Tuhin-thinks** [comment]
You can suggest some name. 

### Here are few suggestions:
1. **VS-Connect**
2. **Virtual FS (File System) Connect**
3. **Remote Explorer**

**Comment by VikramNagwal** [comment]
how about "FileVista"?
